import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  apiReferenceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'developers/api-reference',
    },
  ],
  developersSidebar: [
    {
      type: 'category',
      label: 'Architecture',
      items: [{type: 'autogenerated', dirName: 'developers/architecture'}],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{type: 'autogenerated', dirName: 'developers/api'}],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      items: [{type: 'autogenerated', dirName: 'developers/infrastructure'}],
    },
    {
      type: 'category',
      label: 'Voice AI',
      items: [{type: 'autogenerated', dirName: 'developers/voice-ai'}],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{type: 'autogenerated', dirName: 'developers/reference'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Data Models',
      items: [{type: 'autogenerated', dirName: 'developers/data-models'}],
    },
    {
      type: 'category',
      label: 'Glossary',
      items: [{type: 'autogenerated', dirName: 'developers/glossary'}],
    },
  ],
  guidesSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'guides/getting-started'}],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Board Meetings',
      items: [{type: 'autogenerated', dirName: 'guides/board-meeting'}],
    },
    {
      type: 'category',
      label: 'Integration',
      items: [{type: 'autogenerated', dirName: 'guides/integration'}],
    },
    {
      type: 'category',
      label: 'Commands',
      items: [
        {
          type: 'category',
          label: 'Timeblock',
          items: [{type: 'autogenerated', dirName: 'guides/commands/timeblock'}],
        },
        {
          type: 'category',
          label: 'Planning',
          items: [{type: 'autogenerated', dirName: 'guides/commands/planning'}],
        },
        {
          type: 'category',
          label: 'PIV Loop',
          items: [{type: 'autogenerated', dirName: 'guides/commands/piv-loop'}],
        },
        {
          type: 'category',
          label: 'Release',
          items: [{type: 'autogenerated', dirName: 'guides/commands/release'}],
        },
        {
          type: 'category',
          label: 'Maintenance',
          items: [{type: 'autogenerated', dirName: 'guides/commands/maintenance'}],
        },
        {
          type: 'category',
          label: 'Infrastructure',
          items: [{type: 'autogenerated', dirName: 'guides/commands/infrastructure'}],
        },
      ],
      collapsed: true,
    },
  ],
  workflowsSidebar: [
    {
      type: 'category',
      label: 'n8n Templates',
      items: [{type: 'autogenerated', dirName: 'workflows/n8n-templates'}],
      collapsed: false,
    },
  ],
  internalSidebar: [
    {
      type: 'category',
      label: 'SOPs',
      items: [{type: 'autogenerated', dirName: 'internal/sops'}],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Security & GDPR',
      items: [{type: 'autogenerated', dirName: 'internal/security'}],
    },
    {
      type: 'category',
      label: 'Runbooks',
      items: [{type: 'autogenerated', dirName: 'internal/runbooks'}],
    },
  ],
};

export default sidebars;
