import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  developersSidebar: [
    {
      type: 'category',
      label: 'Architecture',
      items: [{type: 'autogenerated', dirName: 'developers/architecture'}],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{type: 'autogenerated', dirName: 'developers/api'}],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      items: [{type: 'autogenerated', dirName: 'developers/infrastructure'}],
    },
  ],
  guidesSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'guides/getting-started'}],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Integration',
      items: [{type: 'autogenerated', dirName: 'guides/integration'}],
    },
  ],
  workflowsSidebar: [
    {
      type: 'category',
      label: 'n8n Templates',
      items: [{type: 'autogenerated', dirName: 'workflows/n8n-templates'}],
      collapsed: false,
    },
  ],
  internalSidebar: [
    {
      type: 'category',
      label: 'SOPs',
      items: [{type: 'autogenerated', dirName: 'internal/sops'}],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Runbooks',
      items: [{type: 'autogenerated', dirName: 'internal/runbooks'}],
    },
  ],
};

export default sidebars;
